[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "contact_form"
authors = [
    {name = "Filip Woźniak", email = "wozniak.contact@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.11"
keywords = ["wagtail", "django"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Framework :: Django",
]
dependencies = [
    "Django>=4.1",
    "Wagtail>=5.0.2",
    "pytest>=7.0.1",
    "python_webpack_boilerplate>=0.0.10",
    "captcha>=0.4",
    "django-widget-tweaks>=1.4.12",
    "wagtail-django-recaptcha>=1.0"
]
version="0.0.1"

[tool.setuptools.packages.find]
include = ["contact_form*"]
namespaces = false