# Generated by Django 4.0.8 on 2023-03-20 09:38

from django.db import migrations, models
import wagtail
from packaging import version

WAGTAIL_VERSION = version.parse(wagtail.__version__)

if WAGTAIL_VERSION < version.parse("7.0"):
    import wagtail.contrib.forms.models as wagtail_forms_models
else:
    try:  # Wagtail 7+ path
        import wagtail.forms.models as wagtail_forms_models
    except ModuleNotFoundError:  # Fallback when new module isn't available
        import wagtail.contrib.forms.models as wagtail_forms_models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='from_address',
            field=models.EmailField(blank=True, max_length=255, verbose_name='from address'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='to_address',
            field=models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail_forms_models.validate_to_address], verbose_name='to address'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='default_value',
            field=models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value'),
        ),
    ]
