# Generated by Django 6.0.1 on 2026-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_form", "0002_alter_contactpage_from_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="captcha_provider",
            field=models.CharField(
                choices=[
                    ("recaptcha", "Google reCAPTCHA"),
                    ("turnstile", "Cloudflare Turnstile"),
                ],
                default="recaptcha",
                help_text="Select the CAPTCHA provider to use for this form.",
                max_length=20,
                verbose_name="CAPTCHA Provider",
            ),
        ),
    ]
