# Generated by Django 6.0.1 on 2026-01-27 16:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_form", "0003_contactpage_captcha_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptchaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recaptcha_public_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Google reCAPTCHA site key (public key)",
                        max_length=255,
                        verbose_name="RECAPTCHA_PUBLIC_KEY",
                    ),
                ),
                (
                    "recaptcha_private_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Google reCAPTCHA secret key (private key)",
                        max_length=255,
                        verbose_name="RECAPTCHA_PRIVATE_KEY",
                    ),
                ),
                (
                    "recaptcha_required_score",
                    models.CharField(
                        blank=True,
                        default="0.85",
                        help_text="Minimum score required for reCAPTCHA V3 (0.0 - 1.0)",
                        max_length=10,
                        verbose_name="RECAPTCHA_REQUIRED_SCORE",
                    ),
                ),
                (
                    "recaptcha_domain",
                    models.CharField(
                        blank=True,
                        default="www.recaptcha.net",
                        help_text="Domain for reCAPTCHA API (e.g., www.recaptcha.net or www.google.com)",
                        max_length=255,
                        verbose_name="RECAPTCHA_DOMAIN",
                    ),
                ),
                (
                    "turnstile_site_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cloudflare Turnstile site key",
                        max_length=255,
                        verbose_name="TURNSTILE_SITE_KEY",
                    ),
                ),
                (
                    "turnstile_secret_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cloudflare Turnstile secret key",
                        max_length=255,
                        verbose_name="TURNSTILE_SECRET_KEY",
                    ),
                ),
            ],
            options={
                "verbose_name": "CAPTCHA",
                "verbose_name_plural": "CAPTCHA",
            },
        ),
    ]
