# Generated by Django 6.0.1 on 2026-01-27 17:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_form", "0004_captchasettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchasettings",
            name="recaptcha_domain",
            field=models.CharField(
                blank=True,
                default="www.recaptcha.net",
                max_length=255,
                verbose_name="Domain",
            ),
        ),
        migrations.AlterField(
            model_name="captchasettings",
            name="recaptcha_private_key",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Private Key"
            ),
        ),
        migrations.AlterField(
            model_name="captchasettings",
            name="recaptcha_public_key",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Public Key"
            ),
        ),
        migrations.AlterField(
            model_name="captchasettings",
            name="recaptcha_required_score",
            field=models.CharField(
                blank=True, default="0.85", max_length=10, verbose_name="Required Score"
            ),
        ),
        migrations.AlterField(
            model_name="captchasettings",
            name="turnstile_secret_key",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Secret Key"
            ),
        ),
        migrations.AlterField(
            model_name="captchasettings",
            name="turnstile_site_key",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Site Key"),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="captcha_provider",
            field=models.CharField(
                choices=[
                    ("recaptcha", "Google reCAPTCHA"),
                    ("turnstile", "Cloudflare Turnstile"),
                ],
                default="recaptcha",
                help_text='Please remember to <a href="/backend/settings/contact_form/captchasettings/1/" target="_blank">configure the settings</a>.',
                max_length=20,
                verbose_name="CAPTCHA Provider",
            ),
        ),
    ]
