# Generated by Django 6.0.1 on 2026-01-27 17:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_form", "0006_alter_captchasettings_turnstile_secret_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchasettings",
            name="turnstile_secret_key",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Secret Key"
            ),
        ),
        migrations.AlterField(
            model_name="captchasettings",
            name="turnstile_site_key",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Site Key"),
        ),
    ]
