# Generated by Django 6.0.1 on 2026-01-28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_form", "0007_alter_captchasettings_turnstile_secret_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="captchasettings",
            name="turnstile_theme",
            field=models.CharField(
                choices=[("auto", "Auto"), ("light", "Light"), ("dark", "Dark")],
                default="auto",
                max_length=10,
                verbose_name="Theme",
            ),
        ),
        migrations.AddField(
            model_name="captchasettings",
            name="turnstile_size",
            field=models.CharField(
                choices=[("normal", "Normal"), ("compact", "Compact")],
                default="normal",
                max_length=10,
                verbose_name="Widget Size",
            ),
        ),
    ]
