# Generated by Django 6.0.1 on 2026-01-28 12:45

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_form", "0008_captchasettings_turnstile_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpage",
            name="from_address",
            field=models.EmailField(
                blank=True, max_length=255, verbose_name="Address from"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="thank_you_text",
            field=wagtail.fields.RichTextField(
                blank=True, verbose_name="Thank You Message"
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="to_address",
            field=models.CharField(
                blank=True,
                help_text="The form submissions will be emailed to these addresses. Please separate multiple recipients by comma.",
                max_length=255,
                verbose_name="Address to",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="default_value",
            field=models.TextField(
                blank=True,
                help_text="Comma or new line separated values supported for checkboxes.",
                verbose_name="Default Value",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("singleline", "Single Line Text"),
                    ("multiline", "Multi Line Text"),
                    ("email", "Email"),
                    ("number", "Number"),
                    ("url", "URL"),
                    ("checkbox", "Checkbox"),
                    ("checkboxes", "Checkboxes"),
                    ("dropdown", "Dropdown"),
                    ("multiselect", "Multiple Select"),
                    ("radio", "Radio Buttons"),
                    ("date", "Date"),
                    ("datetime", "Date/ Time"),
                    ("hidden", "Hidden Field"),
                ],
                max_length=16,
                verbose_name="Field Type",
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="help_text",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Help Text"
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="label",
            field=models.CharField(max_length=255, verbose_name="Label"),
        ),
    ]
